In [8]:
from torcheval.metrics.functional import bleu_score as blue
from torchmetrics.functional import bleu_score as blue_metric
from torchmetrics.functional.text.bert import bert_score

In [19]:
preds = ["i hate making pizza"]
target = ["i like eating pizza"]
# target = [['there is a cat on the mat', 'a cat is on the mat']]
blue(preds, target, n_gram=1), blue_metric(preds, target, n_gram=1, smooth=False)

(tensor(0.5000), tensor(0.5000))

In [20]:
bert_score(preds, target, model_name_or_path='bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The 

{'precision': 0.7993566989898682,
 'recall': 0.7993566989898682,
 'f1': 0.7993566989898682}

In [88]:
import torch
from torchmetrics.text.perplexity import Perplexity
from torchmetrics.functional.text.perplexity import perplexity

test_logits = torch.tensor([
    [[1.0, 0, 0, 0], [1.0, 0, 0, 0]],
    [[0.25, 0.25, 0.25, 0.25], [0.5, 0.5, 0, 0]]
])
targets = torch.tensor([
    [0, 0], 
    [1, 1]
])
test_logits, targets

(tensor([[[1.0000, 0.0000, 0.0000, 0.0000],
          [1.0000, 0.0000, 0.0000, 0.0000]],
 
         [[0.2500, 0.2500, 0.2500, 0.2500],
          [0.5000, 0.5000, 0.0000, 0.0000]]]),
 tensor([[0, 0],
         [1, 1]]))

In [89]:
ppl = Perplexity()

In [90]:
test_logits = torch.tensor([
    [[40.0, 40]],
    [[10, 0]]
])
targets = torch.tensor([
    [0], 
    [0]

])
test_logits, targets

(tensor([[[40., 40.]],
 
         [[10.,  0.]]]),
 tensor([[0],
         [0]]))

In [91]:
ppl(test_logits, targets)

tensor(1.4142)

In [92]:
ppl.compute()

tensor(1.4142)

In [93]:
ppl.reset()

In [94]:
perplexity(test_logits, targets)

tensor(1.4142)

In [97]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("microsoft/deberta-xlarge-mnli")

ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.