In [1]:
import torch
from torchmetrics.text.perplexity import Perplexity
from torchmetrics.functional.text.perplexity import perplexity
from torch.nn.functional import nll_loss, log_softmax

In [2]:
test_logits = torch.tensor([
    [[1.0, 0, 0, 0], [1.0, 0, 0, 0]],
    [[0.25, 0.25, 0.25, 0.25], [0.5, 0.5, 0, 0]]
])
targets = torch.tensor([
    [0, 0], 
    [1, 1]
])
test_logits, targets

(tensor([[[1.0000, 0.0000, 0.0000, 0.0000],
          [1.0000, 0.0000, 0.0000, 0.0000]],
 
         [[0.2500, 0.2500, 0.2500, 0.2500],
          [0.5000, 0.5000, 0.0000, 0.0000]]]),
 tensor([[0, 0],
         [1, 1]]))

In [3]:
test_logits = torch.tensor([
    [[1.0, 0, 0, 0], [1.0, 0, 0, 0]],
    [[0.25, 0.25, 0.25, 0.25], [0.5, 0.5, 0, 0]]
])
targets = torch.tensor([
    [0, 0], 
    [1, 1]
])
l = torch.tensor([
    [[100.0, 0.0, 10.0, 0.1]],
    [[10, 1.0, 0.0, 0.1]]
])
t = targets = torch.tensor([
    [0],
    [1] 
])
# perplexity(test_logits[0].view(1, 2,4), targets[0].view(1,2))
print(perplexity(l, t), nll_loss(log_softmax(l, dim=-1).permute(0,2,1), t))
print(perplexity(l[0].view(1,1,4), t[0].view(1,1)), nll_loss(log_softmax(l[0].view(1,1,4), dim=-1).permute(0,2,1), t[0].view(1,1)))
print(perplexity(l[1].view(1,1,4), t[1].view(1,1)), nll_loss(log_softmax(l[1].view(1,1,4), dim=-1).permute(0,2,1), t[1].view(1,1)))
print(torch.nn.functional.cross_entropy(l[0].view(1,1,4).permute(0,2,1), t[0].view(1,1)))
print(torch.nn.functional.cross_entropy(l[1].view(1,1,4).permute(0,2,1), t[1].view(1,1)))

tensor(90.0270) tensor(4.5001)
tensor(1.) tensor(0.)
tensor(8104.8613) tensor(9.0002)
tensor(0.)
tensor(9.0002)


In [4]:
l.permute(0,2,1).shape

torch.Size([2, 4, 1])

In [5]:
l[0].unsqueeze(0)

tensor([[[100.0000,   0.0000,  10.0000,   0.1000]]])

In [6]:
test_logits[0], targets[0]

(tensor([[1., 0., 0., 0.],
         [1., 0., 0., 0.]]),
 tensor([0]))

In [7]:
ppl = Perplexity()

In [8]:
test_logits = torch.tensor([
    [[40.0, 40]],
    [[10, 0]]
])
targets = torch.tensor([
    [0], 
    [0]

])
test_logits, targets

(tensor([[[40., 40.]],
 
         [[10.,  0.]]]),
 tensor([[0],
         [0]]))

In [9]:
ppl(test_logits, targets)

tensor(1.4142)

In [10]:
ppl.compute()

tensor(1.4142)

In [11]:
ppl.reset()